export { default as Error } from './404/404'
export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
export { default as Time } from './Footer/Time/Time'
export { default as Navigation } from './Navigation/Navigation'
export { default as Sorting } from './Sorting/Sorting'
export { default as RadioBlock } from './Sorting/RadioBlock/RadioBlock'
export { default as RadioBlockSecond } from './Sorting/RadioBlock/RadioBlockSecond'
export { default as Ticket } from './Ticket/Ticket'
export { default as TicketBack } from './Ticket/TicketBack'
export { default as TicketList } from './TicketList/TicketList.jsx'

